branches: 
  - 'main'
preset: "angular"
tagFormat: "${version}"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"
verifyConditions:
  - '@semantic-release/git'
  - "@semantic-release/github"
analyzeCommits:
  - path: "@semantic-release/commit-analyzer"
    releaseRules:
    - type: "feat"
      release: "minor"
    - type: "hotfix"
      release: "patch"
    - type: "patch"
      release: "patch"
    - type: "minor"
      release: "minor"
    - type: "breaking"
      release: "major"
    - type: "chore"
      release: "patch"
    - type: "ci"
      release: "patch"
generateNotes:
  - path: "@semantic-release/release-notes-generator"
    writerOpts:
      groupBy: "type"
      commitGroupsSort:
        - "hotfix"
        - "feat"
        - "perf"
        - "fix"
      commitsSort: "header"
      mainTemplate: |
        {{> header}}

        {{#if noteGroups}}
        {{#each noteGroups}}

        ### ⚠ {{title}}

        {{#each notes}}
        * {{#if commit.scope}}**{{commit.scope}}:** {{/if}}{{text}}
        {{/each}}
        {{/each}}
        {{/if}}
        {{#each commitGroups}}

        {{#if title}}
        ### {{title}}

        {{/if}}
        {{#each commits}}
        {{> commit root=@root}}
        {{/each}}

        {{/each}}

        {{> footer}}
    preset: conventionalcommits
    presetConfig:
      types:
        - type: "feat"
          section: "Features"
        # Tracked bug fix with a hotfix branch
        - type: "hotfix"
          section: "Bug Fixes"
        # Uninmportent fix (CI testing, etc)
        - type: "fix"
          section: "Bug Fixes"
          hidden: false
        - type: "chore"
          section: "Changes"
          hidden: false
        - type: "docs"
          section: "Changes"
          hidden: false
        - type: "doc"
          section: "Changes"
          hidden: false
        - type: "style"
          section: "Changes"
          hidden: false
        - type: "refactor"
          section: "Changes"
          hidden: false
        - type: "perf"
          section: "Changes"
          hidden: false
        - type: "test"
          section: "Changes"
          hidden: false
        - type: ""
          section: "Changes"
          hidden: false
prepare:
  - path: "@semantic-release/git"
  - path: "@semantic-release/changelog"
    changelogFile: "CHANGELOG.md"
publish:
  - path: "@semantic-release/github"

success:
  - "@semantic-release/github"

fail:
  - "@semantic-release/github"